- name: creating ec2_instance
  hosts: local
  connection: local

  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-03c6dffbde757a30b
    zone_id: Z01730921MDPIK694OSXC
    domain_name: abhishekdev.fun

    instances:
    - mongodb
   
  tasks:
    - name: launching the ec2_instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: printing the output
      ansible.builtin.debug:
        msg: "{{ ec2_output}}"
    

          


      