- name: printing default variables
  hosts: local
  connection: local
  vars:
    technology: devops, linux, ansible
  tasks:
   - name: cahnging var to list
     ansible.builtin.debug:
      msg: "courses are: {{  technology | split(',') }}"