- name: printing the loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name : printing the loops
    ansible.builtin.package:
        name: "{{ item }}""
        state: present
    loop:
    - nginx
    - mysql
